// File generated by flutterfire_cli.
// This file provides default Firebase configuration for this app.
// To regenerate, run: flutterfire configure --project=your-firebase-project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZtdvrDq3LtvjpYxyf-PLzcefZa9aNWQ',
    appId: '1:319165697711:android:5cb3cef4ea76a739130e5a',
    messagingSenderId: '319165697711',
    projectId: 'impulsecontrol-27cb6',
    databaseURL: 'https://impulsecontrol-27cb6.firebaseio.com',
  );
}
